language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.5
  - DJANGO=Django==1.5.1
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install coverage $DJANGO --use-mirrors
  - sh -c "if [ '$COVERALLS' != '0' ]; then pip install coveralls; fi"
  - sh -c "if [ '$DJANGO' = 'https://github.com/django/django/tarball/master' ]; then pip install https://github.com/mbraak/django-webtest/tarball/django1.6; fi"

script: coverage run -a --branch --include="simple_history/*" --omit="simple_history/tests/*" setup.py test

matrix:
  include:
   - python: 3.2
     env: DJANGO=Django==1.5.1
   - python: 3.2
     env: DJANGO=https://github.com/django/django/tarball/master
   - python: 3.3
     env: DJANGO=Django==1.5.1
   - python: 3.3
     env: DJANGO=https://github.com/django/django/tarball/master

after_success: coveralls
