language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.0,<2.1"

install:
  - pip install -U coverage codecov
  - pip install -U $DJANGO
  - pip freeze

script: coverage run setup.py test

matrix:
  exclude:
    - python: 2.7
      env: DJANGO="Django>=2.0,<2.1"

after_success: codecov
