language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"

install:
  - pip install -U coverage codecov $DJANGO
  - python -c 'from __future__ import print_function; import django; print("Django " + django.get_version())'

script: coverage run setup.py test

matrix:
  exclude:
   - python: 2.6
     env: DJANGO="Django>=1.6,<1.7"
   - python: 2.6
     env: DJANGO="Django>=1.7,<1.8"
   - python: 2.6
     env: DJANGO="Django>=1.8,<1.9"
   - python: 3.2
     env: DJANGO="Django>=1.4,<1.5"
   - python: 3.3
     env: DJANGO="Django>=1.4,<1.5"

  include:
   - python: 3.4
     env: DJANGO="Django>=1.7,<1.8"
   - python: 3.4
     env: DJANGO="Django>=1.8,<1.9"

after_success: codecov
