language: python
cache:
  pip: true
python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7
- 3.8
install:
- travis_retry pip install tox-travis codecov
script:
- python --version
- tox -a
- tox -v
after_success: codecov
jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: 3.8
    script: skip
    deploy:
      provider: pypi
      user: jazzband
      server: https://jazzband.co/projects/django-simple-history/upload
      distributions: sdist bdist_wheel
      password:
        secure: aFt6pFTwuzSZnYqQpdO9UKtsLplWIBhI7iwH7/aeH2B0hNCvr5pYfZ2UWvQqNh3aIXoJOoIAN5+Na+YGzY+Y54ZAaFAlEtfEiuXe1APuJ0hLuNvo1IJ/t4ABS2aN4W1HEaoVBaykUNHns+Vo3yfIesK4m9qk5TFuMMbdA6vTxg4=
      on:
        tags: true
        repo: jazzband/prettytable
