language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO=Django==1.4.10
  - DJANGO=Django==1.5.5
  - DJANGO=Django==1.6.2
  - DJANGO=https://github.com/django/django/tarball/stable/1.7.x

install:
  - pip install coverage coveralls $DJANGO --use-mirrors

script: coverage run -a setup.py test

matrix:
  exclude:
   - python: 2.6
     env: DJANGO=Django==1.6.2
   - python: 2.6
     env: DJANGO=https://github.com/django/django/tarball/stable/1.7.x
   - python: 3.2
     env: DJANGO=Django==1.4.10
   - python: 3.3
     env: DJANGO=Django==1.4.10

after_success: coveralls
